### ISSUE TITLE
Error in query: ER_BAD_FIELD_ERROR

### ISSUE THREAD

**Issue by kamil-malinski** [dimitrov-adrian/directus-extension-tags-m2m-interface#1]
Hi!

I added the interface to a m2m-field and get the following error in the console:

```
request errored GET 500 /items/tag?limit=10&fields[]=id&fields[]=name&filter=%7B%22_and%22:[%7B%7D,false,%7B%22name%22:%7B%22_contains%22:%22test1%22%7D%7D]%7D&sort=-id 74ms

🚨 select `tag`.`id`, `tag`.`name` from `tag` where (`tag`.`_eq` = false and `tag`.`name` like '%test%') order by `tag`.`id` desc limit 10 - ER_BAD_FIELD_ERROR: Unknown column 'tag._eq' in 'where clause'
```

what is the "_eq"-field that the query is trying to filter for?

**Comment by kamil-malinski** [comment]
it works when I define at least one filter... so it looks like the problem is the building of the query when there is no filter assigned to the field

**Comment by dimitrov-adrian** [comment]
This shouldn't be the case.

Could you provide more info, what is the directus version and db type.

**Comment by kamil-malinski** [comment]
Directus version: 9.10.0
DB-Type: MySQL

I think the problem is in https://github.com/dimitrov-adrian/directus-extension-tags-m2m-interface/blob/main/src/interface.vue at #273 if props.filter is not set

**Comment by dimitrov-adrian** [comment]
Yes indeed. Thanks for the catch

**Comment by kamil-malinski** [comment]
thank you for the quick fix!
