### ISSUE TITLE
input field not being emptied when selecting a suggestion by mouse click

### ISSUE THREAD

**Issue by kamil-malinski** [dimitrov-adrian/directus-extension-tags-m2m-interface#2]
Hi!

I found a minor usability issue: if you select a suggestion by pressing the enter key on your keyboard the input field is being emptied so you can proceed to enter the next tag.

If you select a suggestion by clicking with your mouse the input field is not being emptied and needs to be cleared manually before one can proceed to enter the next tag.

Here's a quick video to demonstrate the issue: https://screenshots.malinski.at/iqQRJD

Cheers

Kamil

**Comment by dimitrov-adrian** [comment]
Well, actually this behaviour is by purpose, for me, it seems to be more natura, when do select to not clear the input. This makes selecting similar items more ease.

But, thinking now, it might be better, if there is an option like "Close on select" or "Clear on select" that will do closing menu and clearing the input, and from other side, to not clear and keep the suggestion list open

**Comment by dimitrov-adrian** [comment]
I tried to implement my intention, but then the selected tags are hidden behind the menu, and the usability is bit weird then.

Now I agree with you, it seems more straight if the value is cleared.
